version: "3.7"
services:
    database:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dbData
        volumes:
            - dbData:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
        restart: always
        ports:
            - 8081:80
volumes:
    dbData: